const BASE=new URL('.',self.registration.scope).pathname;
const CACHE='planner-shell-v76';
const CORE=['','index.html','style.css?v=7','illustrations.css?v=38','app.js?v=59','manifest.webmanifest','flower.svg','assets/doodles/farm-animals-v1.png','assets/sounds/minimal-pop-click-ui-1.mp3','assets/doodles/collection-rabbit-v1.png','assets/doodles/collection-duckling-v1.png','assets/doodles/collection-goat-v1.png','assets/doodles/collection-pony-v1.png','assets/doodles/collection-fox-v1.png','assets/doodles/collection-hedgehog-v1.png','assets/doodles/collection-squirrel-v1.png','assets/doodles/collection-turtle-v1.png','assets/doodles/collection-raccoon-v1.png','assets/doodles/collection-owl-v1.png','assets/doodles/study-work.png?v=8','assets/doodles/doodle-birthday-v2.png?v=2','assets/doodles/doodle-hair-color-v2.png?v=2','assets/doodles/doodle-salon-v2.png?v=2','assets/doodles/doodle-massage-v2.png?v=2','assets/doodles/doodle-workout-v2.png?v=2','assets/doodles/doodle-stretching-v2.png?v=2','assets/doodles/doodle-trash.png?v=2','assets/doodles/doodle-vacuum.png?v=2','assets/doodles/doodle-mop-floor.png?v=2','assets/doodles/doodle-change-bedding.png?v=2','assets/doodles/doodle-shower.png?v=2','assets/doodles/doodle-wash-hair.png?v=2','assets/doodles/doodle-guinea-pig-hay-water.png?v=2','assets/doodles/doodle-doctor-visit.png?v=2','assets/doodles/doodle-return-purchase.png?v=2','assets/doodles/doodle-feed-cat.png?v=1','assets/doodles/doodle-date.png?v=2','assets/doodles/doodle-cat-litter.png?v=2','assets/doodles/doodle-pet-fresh-water.png?v=2','assets/doodles/doodle-brush-cat.png?v=2','assets/doodles/doodle-wash-pet-bowls.png?v=2','assets/doodles/doodle-change-towels.png?v=2','assets/doodles/doodle-clean-windows.png?v=2','assets/doodles/doodle-organize-wardrobe.png?v=2','assets/doodles/doodle-organize-medicine-cabinet.png?v=2','assets/doodles/doodle-pay-credit-v2.png?v=2','assets/doodles/doodle-pay-utilities-v2.png?v=2','assets/doodles/doodle-study-work-v2.png?v=2','assets/doodles/doodle-sheet-extra.png?v=1','assets/doodles/doodle-sheet-selfcare.png?v=1','assets/doodles/pickup-ozon.svg?v=1','assets/doodles/pickup-wildberries.svg?v=1','assets/doodles/pickup-yandex.svg?v=1','assets/doodles/doodle-shoe-wash.png?v=1','assets/doodles/doodle-ironing.png?v=1','assets/doodles/doodle-steamer.png?v=1','assets/doodles/doodle-dog-walk.png?v=1','assets/doodles/doodle-pharmacy.png?v=1','assets/doodles/doodle-vet-pharmacy.png?v=1','assets/doodles/doodle-vet-visit.png?v=1',...Array.from({length:12},(_,i)=>`assets/doodles/doodle-${i}.png?v=7`),...Array.from({length:13},(_,i)=>`assets/doodles/doodle-${i+12}.png?v=1`)].map(path=>BASE+path);
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(CORE)).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim()).then(()=>self.clients.matchAll({type:'window',includeUncontrolled:true})).then(clients=>Promise.all(clients.map(client=>client.navigate(client.url).catch(()=>{}))))));
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;if(event.request.mode==='navigate'){event.respondWith(fetch(event.request).then(response=>{if(response.ok)caches.open(CACHE).then(cache=>cache.put(BASE+'index.html',response.clone()));return response}).catch(()=>caches.match(event.request).then(cached=>cached||caches.match(BASE+'index.html'))));return}event.respondWith(caches.match(event.request).then(cached=>cached||fetch(event.request).then(response=>{if(response.ok&&new URL(event.request.url).origin===location.origin){const copy=response.clone();caches.open(CACHE).then(cache=>cache.put(event.request,copy))}return response}).catch(()=>caches.match(BASE+'index.html'))))});



